// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/(guides)/(features)/webhooks/set-up.mdx?collection=docs&hash=1741039569109"
import * as docs_8 from "../content/docs/(guides)/(features)/webhooks/events.mdx?collection=docs&hash=1741039569109"
import * as docs_7 from "../content/docs/api-reference/(endpoints)/ingest/post.mdx?collection=docs&hash=1741039569109"
import * as docs_6 from "../content/docs/api-reference/(endpoints)/ingest/delete.mdx?collection=docs&hash=1741039569109"
import * as docs_5 from "../content/docs/(guides)/(root)/quickstart.mdx?collection=docs&hash=1741039569109"
import * as docs_4 from "../content/docs/(guides)/(features)/rules-presets.mdx?collection=docs&hash=1741039569109"
import * as docs_3 from "../content/docs/(guides)/(features)/email-templates.mdx?collection=docs&hash=1741039569109"
import * as docs_2 from "../content/docs/(guides)/(features)/appeals.mdx?collection=docs&hash=1741039569109"
import * as docs_1 from "../content/docs/(guides)/index.mdx?collection=docs&hash=1741039569109"
import * as docs_0 from "../content/docs/api-reference/index.mdx?collection=docs&hash=1741039569109"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"api-reference/index.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/api-reference/index.mdx"}, data: docs_0 }, { info: {"path":"(guides)/index.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/index.mdx"}, data: docs_1 }, { info: {"path":"(guides)/(features)/appeals.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/(features)/appeals.mdx"}, data: docs_2 }, { info: {"path":"(guides)/(features)/email-templates.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/(features)/email-templates.mdx"}, data: docs_3 }, { info: {"path":"(guides)/(features)/rules-presets.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/(features)/rules-presets.mdx"}, data: docs_4 }, { info: {"path":"(guides)/(root)/quickstart.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/(root)/quickstart.mdx"}, data: docs_5 }, { info: {"path":"api-reference/(endpoints)/ingest/delete.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/api-reference/(endpoints)/ingest/delete.mdx"}, data: docs_6 }, { info: {"path":"api-reference/(endpoints)/ingest/post.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/api-reference/(endpoints)/ingest/post.mdx"}, data: docs_7 }, { info: {"path":"(guides)/(features)/webhooks/events.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/(features)/webhooks/events.mdx"}, data: docs_8 }, { info: {"path":"(guides)/(features)/webhooks/set-up.mdx","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/(features)/webhooks/set-up.mdx"}, data: docs_9 }], [{ info: {"path":"meta.json","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/meta.json"}, data: {"pages":["(guides)","api-reference"]} }, { info: {"path":"(guides)/meta.json","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/(guides)/meta.json"}, data: {"title":"Documentation","pages":["index","...(root)","---Features---","...(features)"],"description":"Step-by-step tutorials to get started","root":true,"icon":"Book"} }, { info: {"path":"api-reference/meta.json","absolutePath":"/Users/koristuvac/Desktop/iffy/content/docs/api-reference/meta.json"}, data: {"title":"API Reference","pages":["index","---Endpoints---","...(endpoints)"],"description":"Learn how to use our API","root":true,"icon":"SquareChevronRight"} }])